---
- name: Set up Squid Proxy with Basic Authentication
  hosts: localhost
  become: yes
  tasks:
    - name: Install Squid and Apache2-utils
      apt:
        name:
          - squid
          - apache2-utils
        state: present
        update_cache: yes

    - name: Ensure custom configuration directory exists
      file:
        path: /etc/squid/conf.d
        state: directory
        mode: '0755'

    - name: Create custom Squid configuration file
      copy:
        dest: /etc/squid/conf.d/custom.conf
        content: |
          auth_param basic program /usr/lib/squid/basic_ncsa_auth /etc/squid/passwords
          auth_param basic realm proxy
          acl authenticated proxy_auth REQUIRED
          http_access allow authenticated

    - name: Ensure Squid main configuration includes custom configuration
      lineinfile:
        path: /etc/squid/squid.conf
        line: 'include /etc/squid/conf.d/*.conf'
        state: present
        create: yes

    - name: Generate random password for Squid proxy
      command: openssl rand -base64 12
      register: squid_password
      changed_when: false

    - name: Store the generated password in a temporary file
      copy:
        dest: /tmp/squid_password
        content: "{{ squid_password.stdout }}"
        mode: '0600'

    - name: Create Squid password file with the generated password
      command: >
        htpasswd -cb /etc/squid/passwords squid {{ squid_password.stdout }}
      when: not squid_password is skipped

    - name: Schedule deletion of the temporary password file after 24 hours
      command: >
        echo "rm -f /tmp/squid_password" | at now + 24 hours
      when: not squid_password is skipped

    - name: Restart Squid service to apply changes
      service:
        name: squid
        state: restarted
        enabled: yes

    - name: Print the generated password
      debug:
        msg: "The generated Squid proxy password is: {{ squid_password.stdout }}"
